# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "serve is a static http server anywhere you need one."
  homepage "https://github.com/syntaqx/serve"
  url "https://github.com/syntaqx/serve/releases/download/v0.4.0/serve_0.4.0_macos_x86_64.tar.gz"
  version "0.4.0"
  sha256 "65c26515f3ee53030f909e078eeacf8a15cdd7b6d88a8d22dae1da61b04eec8d"

  def install
    bin.install "serve"
  end

  test do
    system "#{bin}/serve version"
  end
end
