# This file was generated by GoReleaser. DO NOT EDIT.
class SwarmApi < Formula
  desc "swarm-api is a simple HTTP server to communicate with Docker Swarm"
  homepage "https://github.com/syntaqx/swarm-api"
  url "https://github.com/syntaqx/swarm-api/releases/download/v0.0.1/swarm-api_0.0.1_darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "2d33fa2b53c7ada9279a470ac546cd615169d7df06f1f0332698aa3129eb7aa2"

  def install
    bin.install "swarm-api"
  end

  test do
    system "#{bin}/swarm-api --version"
  end
end
