# This file was generated by GoReleaser. DO NOT EDIT.
class SwarmApi < Formula
  desc "swarm-api is a dead simple REST API for Docker Swarm"
  homepage "https://github.com/syntaqx/swarm-api"
  url "https://github.com/syntaqx/swarm-api/releases/download/v0.0.2/swarm-api_0.0.2_darwin_amd64.tar.gz"
  version "0.0.2"
  sha256 "5bb8288bd6ebedc64f9dde527202cfe1f70ae6199fccd8d2fc1ceb7db57f092a"

  def install
    bin.install "swarm-api"
  end

  test do
    system "#{bin}/swarm-api --version"
  end
end
